apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-care-app
  labels:
    app: health-care-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-care-app
  template:
    metadata:
      labels:
        app: health-care-app
    spec:
      containers:
      - name: health-care-app-container
        image: vivekguatam07/health-care-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: health-care-app-np-service
  labels:
    app: health-care-app
spec:
  selector:
    app: health-care-app

  type: NodePort
  ports:
  - nodePort: 31032  
    port: 8082
    targetPort: 8082
